# Generated by Django 3.2.16 on 2025-07-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('bulldozer', 'Bulldozer'), ('excavator', 'Excavator'), ('payloader', 'Payloader'), ('crane', 'Crane'), ('backhoe', 'Backhoe')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('deployed', 'Deployed'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('current_job', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
