# Generated by Django 3.2.16 on 2025-07-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.personnel'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('mechanic', 'Mechanic'), ('admin', 'Admin'), ('driver', 'Driver'), ('manager', 'Manager')], max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('routine_check', 'Routine Check'), ('oil_change', 'Oil Change'), ('engine_repair', 'Engine Repair'), ('hydraulic_fix', 'Hydraulic System Fix'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='api.equipment')),
                ('mechanic', models.ForeignKey(limit_choices_to={'role': 'mechanic'}, on_delete=django.db.models.deletion.PROTECT, to='api.personnel')),
            ],
        ),
    ]
