# Generated by Django 3.2.16 on 2025-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250721_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='generated_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
