# Generated by Django 3.2.16 on 2025-07-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_maintenancelog_generated_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
