# Generated by Django 3.2.16 on 2025-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20250722_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='driver',
        ),
        migrations.AddField(
            model_name='job',
            name='personnel',
            field=models.ManyToManyField(related_name='jobs', to='api.Personnel'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='equipment',
        ),
        migrations.AddField(
            model_name='job',
            name='equipment',
            field=models.ManyToManyField(related_name='jobs', to='api.Equipment'),
        ),
    ]
