# Generated by Django 3.2.16 on 2025-07-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20250724_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='current_job',
        ),
        migrations.AddField(
            model_name='personnel',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('bulldozer', 'Bulldozer'), ('excavator', 'Excavator'), ('payloader', 'Payloader'), ('crane', 'Crane'), ('backhoe', 'Backhoe'), ('truck', 'Truck')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='equipment',
            field=models.ManyToManyField(to='api.Equipment'),
        ),
        migrations.AlterField(
            model_name='job',
            name='personnel',
            field=models.ManyToManyField(to='api.Personnel'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.personnel'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('operator', 'Operator'), ('mechanic', 'Mechanic'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20),
        ),
    ]
